services:
  - type: web
    name: algerian-fire-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn application:application"
    plan: free
    branch: main
